queue_rules:
  - name: default
    merge_conditions: []

pull_request_rules:
  - name: FORKHEAD-CANARY-zz91
    conditions:
      - base=main
    actions:
      comment:
        message: forkhead-canary-zz91
